Repository Mobility-Solutions/Transportify, pull requests merged in 2019-12, with the labels that each got.

#44 UT 2843 acabada
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  pubspec.lock
Labels: UT, inválido, terminada

#43 Sprint3/2852
  lib/main.dart
  lib/middleware/Middleware-Guia.md
  lib/middleware/PaqueteBD.dart
  lib/middleware/PuntoTransportifyBD.dart
  lib/middleware/UsuarioBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/enumerados/AuthStatus.dart
  lib/vistas/Authentication/Autenticacion.dart
  lib/vistas/Authentication/iniciarSesion/Google.dart
  lib/vistas/busqueda/BusquedaFormCiudades.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
  lib/vistas/dialog/CiudadDialog.dart
  lib/vistas/dialog/PaquetesDialog.dart
  lib/vistas/dialog/PuntosDialog.dart
  lib/vistas/dialog/UsuariosDialog.dart
  lib/vistas/dialog/ViajeDialog.dart
  lib/vistas/inicio/Authentication/iniciarSesion/EmailAndPassword.dart
  lib/vistas/inicio/Authentication/iniciarSesion/iniciarSesion.dart
  lib/vistas/inicio/Authentication/registrarse/Registrarse.dart
  lib/vistas/inicio/Inicio.dart
  lib/vistas/inicio/RootPage.dart
  lib/vistas/inicio/WaitingScreen.dart
  lib/vistas/inicio/WidgetInicial.dart
  lib/vistas/perfil/PerfilUsuarioView.dart
Labels: UT, en pruebas

#45 Fix bug pantalla inicio
  lib/vistas/inicio/Inicio.dart
  lib/vistas/inicio/InicioPart.dart
Labels: UT, en pruebas

#46 Sprint3/2940
  lib/middleware/PaqueteBD.dart
  lib/vistas/busqueda/BusquedaForm.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/seguimiento/SeguimientoForm.dart
Labels: UT, bugfix, terminada

#47 Sprint3/2941
  lib/middleware/UsuarioBD.dart
  lib/vistas/inicio/Authentication/registrarse/Registrarse.dart
  lib/vistas/perfil/PerfilUsuarioView.dart
Labels: UT, en pruebas

#49 sprint3/2868 - Autoselección ciudad origen usuario
  lib/middleware/PuntoTransportifyBD.dart
  lib/vistas/busqueda/BusquedaFormCiudades.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
  lib/vistas/dialog/CiudadDialog.dart
  lib/vistas/dialog/PaquetesDialog.dart
  lib/vistas/dialog/PuntosDialog.dart
  lib/vistas/dialog/ViajeDialog.dart
  lib/vistas/inicio/Authentication/iniciarSesion/EmailAndPassword.dart
  lib/vistas/inicio/Inicio.dart
Labels: UT, en pruebas

#50 sprint3/2943 - Fix borrar usuario no lo borra del sistema de autenticacion
  lib/middleware/UsuarioBD.dart
  lib/modelos/Usuario.dart
  lib/vistas/inicio/Authentication/iniciarSesion/EmailAndPassword.dart
  lib/vistas/inicio/Authentication/iniciarSesion/iniciarSesion.dart
  lib/vistas/inicio/Inicio.dart
  lib/vistas/inicio/RootPage.dart
  lib/vistas/inicio/WidgetInicial.dart
Labels: UT

#51 Sprint3/2318
  android/app/src/main/AndroidManifest.xml
  lib/middleware/Datos.dart
  lib/middleware/PaqueteBD.dart
  lib/middleware/PuntoTransportifyBD.dart
  lib/middleware/UsuarioBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/PuntoTransportify.dart
  lib/vistas/MapaView.dart
  lib/vistas/busqueda/BusquedaFormCiudades.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
  lib/vistas/dialog/PuntosDialog.dart
  pubspec.lock
  pubspec.yaml
Labels: UT, en pruebas

#56 Sprint3/2348 erik
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  lib/vistas/ajustes/AjustesApp.dart
  lib/vistas/inicio/Inicio.dart
  pubspec.yaml
Labels: UT, falta encargado pruebas

#52 Pull Request Sprint3/2867+2802
  lib/middleware/ActividadBD.dart
  lib/middleware/ComponenteBD.dart
  lib/middleware/Datos.dart
  lib/middleware/IncidenciaBD.dart
  lib/middleware/MultipleCollectionStreamSystem.dart
  lib/middleware/PaqueteBD.dart
  lib/modelos/Incidencia.dart
  lib/modelos/Paquete.dart
  lib/modelos/PuntoTransportify.dart
  lib/modelos/Usuario.dart
  lib/modelos/Viaje.dart
  lib/modelos/enumerados/EstadoActividad.dart
  lib/vistas/actividad/MiActividadBusqueda.dart
  lib/vistas/actividad/MiActividadView.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/inicio/Authentication/iniciarSesion/iniciarSesion.dart
  lib/vistas/inicio/Inicio.dart
  lib/vistas/seguimiento/CustomStepper.dart
  lib/vistas/seguimiento/IncidenciasView.dart
  lib/vistas/seguimiento/SeguimientoForm.dart
  pubspec.lock
  pubspec.yaml
Labels: UT, en pruebas

#53 Sprint3/2867+2802+2696
  lib/middleware/ActividadBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/Viaje.dart
  lib/modelos/enumerados/EstadoPaquete.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
Labels: UT

#54 sprint3/2951
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/icon/transportify-icon.png
  assets/logo.svg
  lib/vistas/inicio/Authentication/iniciarSesion/iniciarSesion.dart
  lib/vistas/inicio/WaitingScreen.dart
  pubspec.lock
  pubspec.yaml
Labels: UT, terminada
