Repository Mobility-Solutions/Transportify, pull requests merged in 2019-11, with the labels that each got.

#20 Sprint2/2753
  lib/main.dart
  lib/middleware/ComponenteBD.dart
  lib/middleware/EnviosBD.dart
  lib/middleware/Middleware-Anexo-Cambios.md
  lib/middleware/Middleware-Guia.md
  lib/middleware/PaqueteBD.dart
  lib/middleware/PaqueteTransportifyBD.dart
  lib/middleware/PuntosBD.dart
  lib/middleware/ViajeBD.dart
  lib/middleware/ViajeTransportifyBD.dart
  lib/modelos/Envio.dart
  lib/modelos/Paquete.dart
  lib/modelos/PuntoTransportify.dart
  lib/modelos/Puntos.dart
  lib/modelos/Usuario.dart
  lib/modelos/Viaje.dart
  lib/vistas/busqueda/BusquedaForm.dart
  lib/vistas/busqueda/BusquedaFormPuntos.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
  lib/vistas/seguimiento/CustomStepper.dart
  lib/vistas/seguimiento/SeguimientoForm.dart
Labels: UT, terminada

#22 Sprint2/2784
  lib/main.dart
  lib/middleware/Datos.dart
  lib/middleware/PuntoTransportifyBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/Viaje.dart
  lib/util/style.dart
  lib/vistas/CiudadDialog.dart
  lib/vistas/PuntosDialog.dart
  lib/vistas/busqueda/BusquedaForm.dart
  lib/vistas/busqueda/BusquedaFormCiudades.dart
  lib/vistas/busqueda/BusquedaFormPuntos.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
Labels: UT, terminada

#23 Sprint2/2728
  lib/modelos/DatosUsuarioActual.dart
  lib/vistas/inicio/Inicio.dart
Labels: UT, dependencia, en pruebas

#26 Fix issue #25
  lib/vistas/Authentication/iniciarSesion/EmailAndPassword.dart
Labels: bugfix

#24 sprint2/2426
  lib/main.dart
  lib/vistas/Authentication/Autenticacion.dart
  lib/vistas/Authentication/iniciarSesion/EmailAndPassword.dart
  lib/vistas/Authentication/iniciarSesion/Google.dart
  lib/vistas/Authentication/iniciarSesion/iniciarSesion.dart
  lib/vistas/Authentication/registrarse/registrarse.dart
  pubspec.lock
  pubspec.yaml
Labels: UT, retrabajo

#27 sprint2/2794
  lib/middleware/ComponenteBD.dart
  lib/middleware/EnviosBD.dart
  lib/middleware/PaqueteBD.dart
  lib/modelos/Envio.dart
  lib/modelos/Paquete.dart
  lib/modelos/Viaje.dart
  lib/vistas/busqueda/BusquedaForm.dart
  lib/vistas/busqueda/BusquedaFormCiudades.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/seguimiento/SeguimientoForm.dart
Labels: UT, en pruebas

#32 Sprint2/2429
  assets/fonts/Quicksand-Bold.ttf
  assets/fonts/Quicksand-Light.ttf
  assets/fonts/Quicksand-Medium.ttf
  assets/fonts/Quicksand-Regular.ttf
  lib/main.dart
  lib/middleware/Datos.dart
  lib/middleware/UsuarioBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/DatosUsuarioActual.dart
  lib/modelos/Usuario.dart
  lib/util/style.dart
  lib/vistas/UsuariosDialog.dart
  lib/vistas/ViajeDialog.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
  lib/vistas/inicio/Inicio.dart
  lib/vistas/perfilUsuarioView.dart
  pubspec.yaml
Labels: UT, en pruebas

#35 Sprint2/2728+2336
  lib/main.dart
  lib/middleware/Datos.dart
  lib/middleware/PaqueteBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/Usuario.dart
  lib/vistas/Authentication/iniciarSesion/iniciarSesion.dart
  lib/vistas/Authentication/registrarse/registrarse.dart
  lib/vistas/ViajeDialog.dart
  lib/vistas/perfilUsuarioView.dart
Labels: UT, falta encargado pruebas

#33 Sprint2/2750
  lib/util/style.dart
  lib/vistas/busqueda/BusquedaFormCiudades.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
Labels: UT, en pruebas

#36 Sprint2/2427(dialog)
  lib/middleware/PaqueteBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/Paquete.dart
  lib/vistas/PaquetesDialog.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/inicio/Inicio.dart
Labels: UT, en pruebas

#37 sprint2/2581
  lib/middleware/ViajeBD.dart
  lib/modelos/Paquete.dart
  lib/vistas/ViajeDialog.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
Labels: UT, en pruebas

#41 Fix bug busqueda paquetes duplicados (UT 2813)
  lib/middleware/ComponenteBD.dart
  lib/modelos/Paquete.dart
  lib/vistas/busqueda/BusquedaForm.dart
  lib/vistas/busqueda/BusquedaPaqueteForm.dart
  lib/vistas/busqueda/BusquedaViajeForm.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
Labels: UT, en pruebas

#42 Mejorar lógica del Usuario (UT 2814)
  lib/main.dart
  lib/middleware/Datos.dart
  lib/middleware/PaqueteBD.dart
  lib/middleware/UsuarioBD.dart
  lib/middleware/ViajeBD.dart
  lib/modelos/DatosUsuarioActual.dart
  lib/modelos/Usuario.dart
  lib/vistas/Authentication/Autenticacion.dart
  lib/vistas/Authentication/iniciarSesion/EmailAndPassword.dart
  lib/vistas/Authentication/iniciarSesion/Google.dart
  lib/vistas/Authentication/registrarse/registrarse.dart
  lib/vistas/PaquetesDialog.dart
  lib/vistas/ViajeDialog.dart
  lib/vistas/creacion/CreacionPaqueteForm.dart
  lib/vistas/creacion/CreacionViajeForm.dart
  lib/vistas/inicio/Inicio.dart
  lib/vistas/seguimiento/SeguimientoForm.dart
Labels: UT, terminada
